language: java
install: true

addons:
  sonarcloud:
    organization: "maksymdolia-github"

jdk:
  - openjdk11

script:
  - mvn clean verify sonar:sonar -Pcoverage

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
