version: '3'
services:
  discovery-service:
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
  book-service:
    container_name: book-service
    build:
      context: ./book-service
      dockerfile: Dockerfile
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-service:8761/eureka
  book-recommendation-service:
    container_name: book-recommendation-service
    build:
      context: ./book-recommendation-service
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-service:8761/eureka