version: '3'
services:
  book-service:
    build:
      context: ./book-service
      dockerfile: Dockerfile
  book-recommendation-service:
    build:
      context: ./book-recommendation-service
      dockerfile: Dockerfile
    ports:
      - '8082:8082'