zuul:
  prefix: /api
  routes:
    book-recommendation:
      path: /**
      serviceId: BOOK-RECOMMENDATION-SERVICE
eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka}